apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-exporter
  labels:
    app: url-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-exporter
  template:
    metadata:
      labels:
        app: url-exporter
    spec:
      containers:
      - name: url-exporter
        image: url-exporter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        env:
        - name: URL_INSTANCE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: URL_LOG_LEVEL
          value: "info"
        volumeMounts:
        - name: config
          mountPath: /etc/url-exporter
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: url-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: url-exporter
  labels:
    app: url-exporter
spec:
  selector:
    app: url-exporter
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP