# Example configuration for URL Exporter
targets:
  - "https://google.com"                           # Google homepage - highly available
  - "https://github.com"                           # GitHub - reliable public service
  - "https://httpbin.org/status/200"               # HTTP testing service
  - "https://jsonplaceholder.typicode.com/posts/1" # JSON API testing service
  - "https://api.github.com"                       # GitHub API
  - "https://httpstat.us/200"                      # HTTP status testing service
  - "https://www.cloudflare.com"                   # Cloudflare - reliable CDN
  - "https://stackoverflow.com"                    # Stack Overflow - popular site
  - "https://docs.docker.com"                      # Docker documentation
  - "https://kubernetes.io"                        # Kubernetes official site

check_interval: 30s        # How often to check each URL
timeout: 10s               # Timeout for each request
listen_port: 8412          # Port to expose metrics on
instance_id: ""            # Optional: custom instance identifier (defaults to hostname)
retries: 3                 # Number of retries for failed requests
log_level: "info"          # Log level: debug, info, warn, error