# Example configuration for URL Exporter
targets:
  # HTTP/HTTPS protocols (checked using HTTP HEAD requests)
  - "https://google.com"                           # Google homepage - highly available
  - "https://github.com"                           # GitHub - reliable public service
  - "https://httpbin.org/status/200"               # HTTP testing service
  - "https://jsonplaceholder.typicode.com/posts/1" # JSON API testing service
  - "https://api.github.com"                       # GitHub API
  - "https://httpstat.us/200"                      # HTTP status testing service
  - "https://www.cloudflare.com"                   # Cloudflare - reliable CDN
  - "https://stackoverflow.com"                    # Stack Overflow - popular site
  - "https://docs.docker.com"                      # Docker documentation
  - "https://kubernetes.io"                        # Kubernetes official site
  - "http://localhost:3000"                       # Local development server
  
  # Non-HTTP protocols (checked using TCP connectivity)
  - "ftp://ftp.gnu.org:21"                        # FTP server connectivity
  - "ssh://github.com:22"                         # SSH connectivity to GitHub
  - "smtp://smtp.gmail.com:587"                   # SMTP server connectivity
  - "telnet://towel.blinkenlights.nl:23"          # Telnet server (Star Wars ASCII)
  - "mysql://localhost:3306"                      # MySQL database connectivity
  - "postgres://localhost:5432"                   # PostgreSQL database connectivity
  - "redis://localhost:6379"                      # Redis connectivity
  - "mongodb://localhost:27017"                   # MongoDB connectivity
  
  # Test cases for error scenarios
  - "https://nonexistent-domain-123.com"          # Nonexistent domain
  - "https://internal.company.local"              # Internal network URL
  - "https://test.invalid"                        # Invalid TLD

checkInterval: 30s        # How often to check each URL
timeout: 10s              # Timeout for each request
listenPort: 8412          # Port to expose metrics on
instanceId: ""            # Optional: custom instance identifier (defaults to hostname)
retries: 3                # Number of retries for failed requests
logLevel: "info"          # Log level: debug, info, warn, error